### ISSUE TITLE
Problem in function "process_optical_flow"

### ISSUE THREAD

**Issue by SleepEaaarly** [kaichen-z/DynPoint#4]
When running your code, I found after going through funtion "process_optical_flow" the output flow picture size didn't match the input height and width. Specifically, my input height is 288 and width is 540. The output former_1_2 is (2,1,2,288,536) and the same condition with former_2_1, which means the output flow picture is 288 * 536. I suspected it was changed by "model_flow" which is RAFT.
I also noticed in the end of this function you were trying to resize the flow picture by function "interpolate". However, the input params of this func which are H, W, H_flow, W_flow always equal, which means it was impossible to get into this "else" branch.
All in all, is there a bug in this function or how could i use 288 * 540 photos to go through this function?

**Comment by kaichen-z** [comment]
Hello, thank you for your interest. If the width or height of your input is not a multiple of 8, its dimensions will be adjusted. For example, if your input resolution is 288 x 540, you would need to interpolate it to 288 x 536 before feeding it into FlowNet. After obtaining the output, you'd resize it back to 288 x 540.

**Comment by SleepEaaarly** [comment]
Thanks very much for your reply! Hoping for your following code!
